### ISSUE TITLE
Unable to authorize the application

### ISSUE THREAD

**Issue by rvschuilenburg** [pcperini/Tusk---Issues#2]
## Expected Behavior
Being able to login to my mastodon instance.

## Actual Behavior
I get redirected to the authorization page of my instance, but after clicking the 'authorize' button and redirecting back to the app, the authorization never happens and the application shows an empty timeline.

## Steps to Reproduce the Problem

  1. Start up Tusk
  2. In the pop-up window to login and select an instance, type 'mastodon.social' (though this also didn't work with my own instance, toot.agency)
  3. Click Login
  4. In the new Safari window, login, or if already logged in, press the blue "Authorize" button.
  5. In the pop-up, click on "Open in Tusk".

Then the app opens, but i see a timeline with a loading icon. The Tusk app also does not show up when i go to my profile settings in the selected instance under "Authorized Applications". So it appears the authorization never completes successfully.

## Specifications

  - Version:1.0.0 build 8
  - Platform: iOS 12.0 (i do now realize i'm running a beta Version of iOS. Could this be the issue?)
  - Subsystem:

**Comment by jconnary** [comment]
I'm experiencing the same issue. I will add that if I click on the Profile icon on the far right the app crashes. When the app is reopened it asks for me to login by entering the instance name again.

iOS 12 PB 7 iPhone 7+

**Comment by moritzheiber** [comment]
What are the Mastodon server versions you are connecting to?

**Comment by jconnary** [comment]
mastodon.host and mastodon.technology are both v2.4.3, mastodon.social is v2.5.0RC1

**Comment by moritzheiber** [comment]
Okay, for me the authentication to `mastodon.social` worked flawlessly this morning. Have you tried uninstalling an re-installing the app? (just trying to weed out a few edge cases)

**Comment by jconnary** [comment]
Still doesn't work after deleting and reinstalling the app. Same behaviour.

**Comment by rvschuilenburg** [comment]
Hah. I’m now running into a separate issue I probably should report separately; authentication on mastodon.social indeed works perfectly now. So I wanted to logout so I could login to my own instance. However, there is no logout button

**Comment by rvschuilenburg** [comment]
Whoops hit the wrong button :) it indeed works for me on mastodon.social now. Still have to try it with my own instance.

**Comment by tonilampela** [comment]
Same issue here with my personal instance mastodon.toni.im. iOS 12 Public Beta 10, build 24 of Tusk, instance is running 2.4.5.

**Comment by charliemchapman** [comment]
I'm getting the same issue with mastodon.social on my iPhone 6s running iOS 12 Beta

**Comment by huxinq** [comment]
![055678c8-95cd-4bb9-825f-8d53c3b54b0d](https://user-images.githubusercontent.com/14837634/44965345-915bb980-af67-11e8-9250-a3b0986edaae.jpeg)
I’m also getting this.  iPhone 6s running the latest iOS 12 developer beta on ohnomy.rocks.

**Comment by tonilampela** [comment]
Updating to build 25 seems to have fixed the authentication error for me.

**Comment by anselmh** [comment]
I’m getting the same error with the latest build, also with the NSPOSIX Code 53 error as stated in the screenshot above.

Using Phone 7 with iOS12 (lastest public beta, build 16A5366a).

**Comment by moritzheiber** [comment]
Just for consistencies sake.. it appears to be an issue with the iOS 12 beta, am I correct? I don’t see any other users posting a report here except for people with the beta.

The error makes me think this is somehow TLS related (cipher mismatch, certificate error etc.), but I’ll reserve judgement for now.

**Comment by forgottentowel** [comment]
Same issue here: latest iOS 12 beta, iPhone 7 Plus

**Comment by jmreekes** [comment]
I’m getting the same error. I’m running iOS 12 on an iPhone 6s.

**Comment by huxinq** [comment]
Considering that this a beta-testing, iOS 12-running bunch, the fact that the newest devices reported are iPhone 7 (Plus) is probably significant.

**Comment by charliemchapman** [comment]
After the latest update, I uninstalled and reinstalled the app and I could authenticate successfully and load everything after that.

This doesn't seem to be working for other people who have the issue, just tossing it out for others to try.

iPhone 6s running iOS 12 beta

**Comment by julienXX** [comment]
Uninstalling and re-installing fixed the issue for me (ios 12 on iphone 7).

**Comment by forgottentowel** [comment]
Not for me (iOS 12, iPhone 7 Plus, MastoHost instance)

**Comment by tewha** [comment]
At the risk of pointing out the obvious/useless, I've had iOS 12 network bugs go away on a device restart. Have you guys tried that yet?

**Comment by jmreekes** [comment]
Restarts, and app delete/re-install have not fixed the issue for me

**Comment by anselmh** [comment]
So this is likely a change in iOS12 that targets performance, battery and security. As far as I found out [this might be very likely because](https://forums.developer.apple.com/thread/106838#328512) the connection request is made when the app is in background but the app didn’t request permission from iOS for that. I don’t have much more to find out as I don’t have the source of Tusk. But maybe this helps solving the issue.

**Comment by pcperini** [comment]
I've added as many of you as I could to a group to test b30, which is an attempt to fix this bug. If you don't have access to b30, DM me your TestFlight email! If you do, let me know if it resolves the issue!

**Comment by philippec** [comment]
b30 did resolve this for me. Thanks!

**Comment by lukewestby** [comment]
fixed as heck. thank you!

**Comment by huxinq** [comment]
Fixed! Thanks pcperini.

**Comment by rvschuilenburg** [comment]
Also fixed for me 👍

**Comment by anselmh** [comment]
Seeems to be fixed, yes!

**Comment by pcperini** [comment]
Woo! Closing now <3

**Comment by nathanwentworth** [comment]
b30 fixed this, thank you!

**Comment by jconnary** [comment]
Not fixed for me or I'm experiencing a different bug. Clicking on the gear icon has no effect (not sure if it's supposed to or not).


![c4b5c9c2-cf54-4a6a-ba74-7e21628df646](https://user-images.githubusercontent.com/853620/45370551-cbbcfa80-b5e8-11e8-8bbc-523632e54947.png)
![92a5642b-f8c8-4073-b97b-dc201140c0f8](https://user-images.githubusercontent.com/853620/45370552-cbbcfa80-b5e8-11e8-82e9-5ec1ff19c7b1.png)

**Comment by aurynn** [comment]
b30 resolved the error for me as well, on iOS 12. 🙂 thanks!

**Comment by phoneboy** [comment]
This issue is resolved for me with some instances but not others.
Specifically noagendasocial.com.

**Comment by pcperini** [comment]
Any "access token" errors wipe auth, and a hard-relaunch will launch clean. This might help y'all out. In the meantime, I'm going to ground-up redesign auth—it's DEFINITELY still messy.

**Comment by jconnary** [comment]
Beta 32 seems to have cleared everything out and I was successfully able to log into my instance. Thanks!
