### ISSUE TITLE
Pinned posts not interactive

### ISSUE THREAD

**Issue by 0q98ahdsg3987y1h987y** [pcperini/Tusk---Issues#22]
## Expected Behavior
Able to tap hashtags or view thread for pinned posts on any profile

## Actual Behavior
No touch events register. Swiping to see thread freezes the toot, sometimes the app, in rare cases terminates the application

## Steps to Reproduce the Problem

  1. Go to own profile or random user profile with pinned post
  2. Tap links, usernames, hashtags or swipe for thread view

## Specifications

  - Version: 1.0.0b26
  - Platform: iOS 11
  - Subsystem: (what do you want us to put here?)

**Comment by pcperini** [comment]
Fixed in b31
