### ISSUE TITLE
Tapping toot in notification tab opens WebView

### ISSUE THREAD

**Issue by 0q98ahdsg3987y1h987y** [pcperini/Tusk---Issues#23]
## Expected Behavior
Probably intentional? But seems odd. I’d expect to go to the toot in app

## Actual Behavior
The toot opens in a webview

## Steps to Reproduce the Problem

Tap toot in notification tab

## Specifications

  - Version: 1.0.0b26
  - Platform: iOS11

**Comment by pcperini** [comment]
This is a remnant of "redirect to the website" being a workaround for nonexistent functionality. Definitely a bug now!

**Comment by pcperini** [comment]
This is fixed in b35
