### ISSUE TITLE
DMs are not loading

### ISSUE THREAD

**Issue by bitboxer** [pcperini/Tusk---Issues#28]
## Expected Behavior

Dms loading. 

## Actual Behavior

Spinning wheel. 

## Steps to Reproduce the Problem

  1. Open app
  1. Go to dm tab
  1. See spinner

## Specifications

  - Version: 1.0.0 (26)
  - Platform: iOS
  - Subsystem:

**Comment by pcperini** [comment]
Is this still happening after b30?

**Comment by bitboxer** [comment]
No, this works now. Thanks 🙇
