### ISSUE TITLE
Properly detecting missing / failing authorization

### ISSUE THREAD

**Issue by rvschuilenburg** [pcperini/Tusk---Issues#3]
## Expected Behavior
The app should correctly detect it if the authorization has been pulled server-side.

## Actual Behavior
There is currently no button for logging out / unlinking your account inside the app. When the authorization is removed on the server side, the app will get stuck in an endless loop.

## Steps to Reproduce the Problem

  1. Go to your preference in the web interface of your instance
  2. Go to "Authorized apps"
  3. Remove the authorization for Tusk.

Now when you open tusk, the timeline will try to load, but fail, resulting in an endless loop. Restarting the app or reinstalling the app does not fix this.

## Specifications

  - Version: 1.0.0 (build 15)
  - Platform: iOS 12
  - Subsystem:

**Comment by rvschuilenburg** [comment]
Ran into this because #2 was fixed, haha. Logging in is working correctly now for mastodon.social, but i wanted to give it a try on my own instance. Because there was no logout button anywhere, i decided to pull the authorized app from my settings on the server.

**Comment by rvschuilenburg** [comment]
Since the latest build (which is a bit more verbose when there are errors), i do see an error popup;

> mastodonError("The access token is invalid")

However, restarting the application (as mentioned in the changelog), or even restarting the device, has no effect. But i think we're moving in the right direction.

**Comment by pcperini** [comment]
This should be "fixed" in b25, in that once you encounter `The access token in invalid`, a relaunch will reset your authentication state entirely.

Auth and onboarding are due for a major overhaul, but this should have a workaround now. Mind confirming?

**Comment by rvschuilenburg** [comment]
I'm currently running build 27, but I'm still only getting the `mastodonError("The access token is invalid")` but no new authentication state after relaunching the app. 
Is it possible to reset the authentication state when the error is thrown, instead of after a relaunch?

**Comment by rvschuilenburg** [comment]
This appears to be fixed for me in beta 30.

**Comment by pcperini** [comment]
Closing for now, but I'm intending on redesigning the auth flow substantially to make this a less jarring process.
