### ISSUE TITLE
Swiping toot to show replies crashes app

### ISSUE THREAD

**Issue by tonilampela** [pcperini/Tusk---Issues#37]
Occasionally when swiping a toot to show replies it causes whole app to crash. Subsequent swipe for same toot works fine. This has occurred in multiple builds on iOS 12 latest public beta both on iPhone and iPad.

**Comment by grantjbutler** [comment]
I've also seen this behavior. I can try to grab a crash report the next time it happens and upload it if that will help.

**Comment by grantjbutler** [comment]
I experienced the crash on the way into work. Attached is the crash log tat was generated. [Tusk-2018-09-05-123819.crash.zip](https://github.com/pcperini/Tusk---Issues/files/2354022/Tusk-2018-09-05-123819.crash.zip)

**Comment by pcperini** [comment]
Fixed in b31
