### ISSUE TITLE
Crash On Launch

### ISSUE THREAD

**Issue by jnozzi** [pcperini/Tusk---Issues#51]
Crashes on launch. I force-quit and tried again, no luck. The task switching snapshot (even after relaunch) shows that I was viewing someone’s profile and it looks like it’s trying to restore that state even after force-quit but the home tab icon is lit and it’s clearly trying to load the timeline at the moment it crashes. 

## Specifications

  - Version: 1.0.0 (31)
  - Platform: iOS 12 Beta 12

**Comment by jnozzi** [comment]
Seems to be resolved in build 32. Huh.

**Comment by pcperini** [comment]
I think this might be a side effect of the fix. I pretty much broke data propagation in b31, fixed in b32. Think I should close this out?

**Comment by jnozzi** [comment]
Yeah, I haven't gotten it to crash yet.
