### ISSUE TITLE
Faves UX

### ISSUE THREAD

**Issue by jnozzi** [pcperini/Tusk---Issues#54]
The Favs UX is a little awkward. The location of the star suggests “fave this account of mine”. It really should be in the account info table since it’s a “property of” the account and needs a “My Favorites” label to explain its purpose.

**Comment by pcperini** [comment]
Definitely agree. Not happy with the UI for this. What would you think about a table row underneath "Following" for your own profile?

**Comment by jnozzi** [comment]
Sounds like an appropriate place to me. 😋
