### ISSUE TITLE
Thread View Perpetual Loading

### ISSUE THREAD

**Issue by jnozzi** [pcperini/Tusk---Issues#55]
In b33, if you swipe to view a thread with no replies (single post), the loading spinner never goes away.

**Comment by moritzheiber** [comment]
This is true for any thread I think, i.e. anything that's potentially threaded has the perpetual spinner appended to it.

**Comment by jnozzi** [comment]
@moritzheiber I believe you're right about that. I admit I can't use Tusk for day-to-day because it doesn't yet have multi-account support, so I miss details. :-)
