### ISSUE TITLE
Long pressing on CW content flashes on non-main-timeline views 

### ISSUE THREAD

**Issue by zacbir** [pcperini/Tusk---Issues#56]
## Expected Behavior

Long press should disclose the content

## Actual Behavior

Long press when looking at a toot with content warning in my own profiles list of toots just flashes, it looks as though the cell expand to accommodate the protected content, but nothing shows.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: 1.0.0 (34)
  - Platform: iOS 11.4
  - Subsystem:

**Comment by zacbir** [comment]
I can't seem to add an attachment, but I've got a screen recording of it.

**Comment by pcperini** [comment]
This should be resolved in b30-something 😆
